[project]
name = "methodes-computationnelles"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "bertopic>=0.17.4",
    "ipykernel>=7.3.0",
    "ipysigma>=0.24.6",
    "ipywidgets>=8.1.9",
    "nbformat>=5.11.1",
    "networkx>=3.6.1",
    "notebook>=7.6.2",
    "pandas>=3.0.5",
    "pip>=26.2.1",
    "plotly>=7.0.0",
    "numpy==2.4.6",
    "scipy==1.17.1",
    "scikit-learn==1.9.0",
    "numba==0.66.0",
    "llvmlite==0.48.0",
    "hdbscan==0.8.44",
    "umap-learn==0.5.12",
    "torch==2.13.0",
    "sentence-transformers==5.6.0",
    "transformers==5.14.1",
    "stopwordsiso>=0.7.1",
]
